name: SimpleBroadcast
main: SimpleBroadcast\SimpleBroadcast
author: Dutok
version: 2.0
api: [3.0.0, 4.0.0]
commands:
 broadcast:
  permission: simplebroadcast.broadcast
  description: Broadcasts your message.
permissions:
 simplebroadcast:
  default: op
  description: Top level permission
  children:
   simplebroadcast.broadcast:
    default: op
    description: Allows you to broadcast.
